### ISSUE TITLE
Remove QT classes from filetools

### ISSUE THREAD

**Issue by duncan-r** [duncan-r/SHIP#9]
These were in for convenience in an early internal version of the library. They don't make a lot of sense being there any more.

Perhaps mark as deprecated?

**Comment by JamesRamm** [comment]
:+1: for this. 
I think just straight removing them would be Ok (since not yet any pypi release). Looks like there is a git tag people can fall back on if reliant on this

**Comment by JamesRamm** [comment]
There is a function - `directoryFileNames` in `filetools` that like the QT classes isn't used by the rest of the library; is this intended as part of a public api, or could also be removed?

**Comment by duncan-r** [comment]
Ha! I expect I rely on this in a few place. If you feel like ripping it out while wandering around in there then go for it. I've been meaning to update the uses of this for ages and it will force me to get around to it.

`directoryFilenames()` : 
I think this will also have been part of our internal tool set. I can't imagine that it's particularly useful for the library. I think get rid.

**Comment by JamesRamm** [comment]
Cool...I'll jump on this change now then
